name=simpleHC_SR04
version=1.0.1
author=timothy <timflytosky@outlook.com>
maintainer=timothy <timflytosky@outlook.com>
sentence=A library uning HC_SR04.
paragraph=You can use HC_SR04 but non-blocking.
category=Sensors
url=https://github.com/timflytosky/simpleHC_SR04
architectures=*
includes=simpleHC_SR04.h
